apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbapp
spec:
  selector:
    matchLabels:
      app: sbapp
  replicas: 2
  template:
    metadata:
      labels:
        app: sbapp
    spec:
      containers:
      - name: sbapp
        image: springio/raspberrypimicrok8sjava
        imagePullPolicy: Never
        ports:
        - name: sbapp
          containerPort: 8083
          protocol: TCP