apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo-deployment1
  labels:
    app: spring-boot-demo
spec:
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
      - name: raspberrypimicrok8sjava1
        image: springio/raspberrypimicrok8sjava
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
